name: Publish to NPM
# on:
#   release:
#     types: [created]
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: packages/express-typed
      # no need to build the package, prepublish script will take care of it
      - name: Run tests
        run: pnpm test
        working-directory: packages/express-typed
      - name: get version
        id: get_version
        run: echo version=v$(node -p "require('./package.json').version") >> $GITHUB_OUTPUT
        # run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")
      - name: Publish package on NPM 📦
        run: npm publish --tag alpha
        working-directory: packages/express-typed
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      version: ${{ steps.get_version.outputs.version }}

  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          needs: build-and-push
          run: gh release create "${{ needs.build-and-push.outputs.version }}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${{ needs.build-and-push.outputs.version }}" \
            --generate-notes
